# Generated by Django 5.1.7 on 2025-04-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_alter_product_price_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
