# Generated by Django 5.1.7 on 2025-04-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0006_alter_product_price_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
