# Generated by Django 5.1.7 on 2025-04-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0006_alter_product_price_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
