# Generated by Django 5.1.7 on 2025-04-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_alter_product_options'),
        ('secondapp', '0007_alter_product_price_alter_product_product_id'),
    ]

    operations = [
    ]
