# Generated by Django 5.1.7 on 2025-04-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0008_merge_20250407_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
