# Generated by Django 5.1.7 on 2025-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0010_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
